### ISSUE TITLE
Transformer.from_crs() got an unexpected keyword argument 'skip_equivalent'

### ISSUE THREAD

**Issue by simonw** [simonw/shapefile-to-sqlite#15]
Getting this error:
```
zip://timezones-with-oceans.shapefile.zip
  [------------------------------------]    0%
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/timezones-api-Lb_JnQTU/bin/shapefile-to-sqlite", line 8, in <module>
    sys.exit(cli())
  File "/Users/simon/.local/share/virtualenvs/timezones-api-Lb_JnQTU/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/timezones-api-Lb_JnQTU/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/share/virtualenvs/timezones-api-Lb_JnQTU/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/share/virtualenvs/timezones-api-Lb_JnQTU/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/timezones-api-Lb_JnQTU/lib/python3.10/site-packages/shapefile_to_sqlite/cli.py", line 105, in cli
    db_table = utils.import_features(
  File "/Users/simon/.local/share/virtualenvs/timezones-api-Lb_JnQTU/lib/python3.10/site-packages/shapefile_to_sqlite/utils.py", line 50, in import_features
    transformer = Transformer.from_crs(
TypeError: Transformer.from_crs() got an unexpected keyword argument 'skip_equivalent'
```

**Comment by simonw** [comment]
https://pyproj4.github.io/pyproj/stable/history.html#id2 says that in `pyproj` 3.4.0:

> -   CLN: Remove deprecated `skip_equivalent` kwarg from transformers and `errcheck` kwarg from [`CRS.from_cf()`](https://pyproj4.github.io/pyproj/stable/api/crs/crs.html#pyproj.crs.CRS.from_cf "pyproj.crs.CRS.from_cf") (pull #1077)

**Comment by simonw** [comment]
Ran `pip install -U pyproj` in my local environment and now I can see this error locally too (previously I had `pyproj-2.6.1.post1`).

`pytest` now says:

```
================================================================== short test summary info ===================================================================
FAILED tests/test_shapefile_to_sqlite.py::test_import_features[None] - TypeError: from_crs() got an unexpected keyword argument 'skip_equivalent'
FAILED tests/test_shapefile_to_sqlite.py::test_import_features[customtable] - TypeError: from_crs() got an unexpected keyword argument 'skip_equivalent'
FAILED tests/test_shapefile_to_sqlite.py::test_import_features_spatialite - TypeError: from_crs() got an unexpected keyword argument 'skip_equivalent'
FAILED tests/test_shapefile_to_sqlite.py::test_import_features_spatialite_with_custom_crs - TypeError: from_crs() got an unexpected keyword argument 'skip_...
FAILED tests/test_shapefile_to_sqlite.py::test_import_features_spatial_index - TypeError: from_crs() got an unexpected keyword argument 'skip_equivalent'
FAILED tests/test_shapefile_to_sqlite.py::test_import_features_extract_columns - TypeError: from_crs() got an unexpected keyword argument 'skip_equivalent'
FAILED tests/test_shapefile_to_sqlite.py::test_import_features_extract_columns_spatialite - TypeError: from_crs() got an unexpected keyword argument 'skip_...
=== 7 failed, 1 passed in 2.40s ===
```
