### ISSUE TITLE
Figure out how to handle projections

### ISSUE THREAD

**Issue by simonw** [simonw/shapefile-to-sqlite#6]
The county park shapefiles from #5 use [EPSG:2227](https://spatialreference.org/ref/epsg/nad83-california-zone-3-ftus/) (California 3) as their projection.

I had to hack the script around to import the data correctly. I replaced 4326 with 2227 in a couple of places:

https://github.com/simonw/shapefile-to-sqlite/blob/2fcec0316bff2a6715261a6cf6156b5dd5046aa7/shapefile_to_sqlite/utils.py#L62

https://github.com/simonw/shapefile-to-sqlite/blob/2fcec0316bff2a6715261a6cf6156b5dd5046aa7/shapefile_to_sqlite/utils.py#L90

Then to get the data to show correctly as a GeoJSON-powered map I had to use this in the queries:

`select AsGeoJSON(Transform(geometry, 4326)) as geojson ...`

Demo: https://santa-clara-county-parks-j7hipcg4aq-uc.a.run.app/parks/park_boundary_maps

**Comment by simonw** [comment]
If you're using `--spatialite` you can at least use `Transform()` in SQL to get back the 4326 projection. Without the `--spatialite` option we store GeoJSON directly in the database, so it would be convenient if we could transform it prior to storage (if the user chooses to do so).

**Comment by simonw** [comment]
I'm inclined to default to transforming to [4326 / WGS 84](https://spatialreference.org/ref/epsg/wgs-84/) - especially for the non-spatialite case. The GeoJSON RFC https://tools.ietf.org/html/rfc7946#section-4 specifies WGS 84.

Fiona can read the projection of the shapefile as `collection.crs` - though this comes back as a dictionary and I need to be confident I can turn that into arguments I can use to project the data to WGS 84.

I need to design command-line options that can be used to tell the tool NOT to project to WGS 84, and maybe to specify alternative projections.

**Comment by simonw** [comment]
I have an example of how to use `pyproj` to project geometries here: https://github.com/simonw/cryptozoology/blob/aa23eb806ba08d7aa3765bc76a0479c059f2fabf/scripts/bigfoot/derive_bigfoot_range.py#L39-L67

**Comment by simonw** [comment]
Potential design:
* `--keep-projection` - keep whatever projection the shapefile is already in
* `--project=ref` - convert to and store using this projection

I'm aware that I'm not particularly familiar with jargon usage in the GIS world, so I'm worried I may not be designing these in a way that is consistent with other tools. https://proj.org/usage/quickstart.html is one tool that appears to be widely used, not sure if I can emulate parts of its CLI design or not though.

**Comment by simonw** [comment]
http://resources.esri.com/help/9.3/arcgisengine/java/gp_toolref/environment_settings/output_coordinate_system.htm

What we're defining here is the coordinate system that will be stored in the database. This may differ from the coordinate system that was used in the shapefile.

**Comment by simonw** [comment]
https://gdal.org/programs/ogr2ogr.html

Uses:

> ` -a_srs <srs_def>`
>     Assign an output SRS. Srs_def can be a full WKT definition (hard to escape properly), or a well known definition (i.e. EPSG:4326) or a file with a WKT definition.

**Comment by simonw** [comment]
SRS = spatial reference system
CRS = coordinate reference system

As far as I can tell these two terms mean exactly the same thing: https://en.wikipedia.org/wiki/Spatial_reference_system

**Comment by simonw** [comment]
I like the look of the `pyproj` `CRS.from_user_input()` method:
```
from pyproj import CRS
CRS.from_user_input??                                                                                                                                           
Signature: CRS.from_user_input(value)
Source:   
    @classmethod
    def from_user_input(cls, value):
        """
        Initialize a CRS class instance with:
          - PROJ string
          - Dictionary of PROJ parameters
          - PROJ keyword arguments for parameters
          - JSON string with PROJ parameters
          - CRS WKT string
          - An authority string [i.e. 'epsg:4326']
          - An EPSG integer code [i.e. 4326]
          - A tuple of ("auth_name": "auth_code") [i.e ('epsg', '4326')]
          - An object with a `to_wkt` method.
          - A :class:`~pyproj.crs.CRS` class

        Parameters
        ----------
        value : obj
            A Python int, dict, or str.

        Returns
        -------
        CRS
        """
```

**Comment by simonw** [comment]
I think I'll use these as the arguments:
```
    --keep-crs - keep whatever CRS the shapefile is already in
    --crs=ref - convert to and store using this CRS
```

**Comment by simonw** [comment]
Maybe even simplify this to one option by allowing `--crs=keep` as a special value. `keep` doesn't currently have a meaning as a CRS reference:
```
>>> from pyproj import CRS
>>> CRS.from_user_input('keep')                                                                                                                                      
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/simonw/.local/share/virtualenvs/shapefile-to-sqlite-53xajEHi/lib/python3.7/site-packages/pyproj/crs.py", line 580, in from_user_input
    return cls(value)
  File "/Users/simonw/.local/share/virtualenvs/shapefile-to-sqlite-53xajEHi/lib/python3.7/site-packages/pyproj/crs.py", line 436, in __init__
    super(CRS, self).__init__(projstring)
  File "pyproj/_crs.pyx", line 1738, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: keep: (Internal Proj Error: proj_create: unrecognized format / unknown name)
```

**Comment by simonw** [comment]
I'm seeing poor performance from the transforms. The shapely manual suggests this would be faster:

    project = pyproj.Transformer.from_proj(proj_in, proj_out).transform

**Comment by simonw** [comment]
MUCH faster now that I switched to using the `pyproj.Transform` class.

**Comment by simonw** [comment]
I could add a `-v` verbosity option which causes it to output useful debugging information on the CRS that are being used.

**Comment by simonw** [comment]
Important comment:

https://github.com/simonw/shapefile-to-sqlite/blob/d1337bc772fc85607b5fec9c384286a54f19e7a5/shapefile_to_sqlite/cli.py#L74-L82

This had me puzzled for quite a while: I kept getting this error:

```
  File "/Users/simonw/Dropbox/Development/shapefile-to-sqlite/shapefile_to_sqlite/utils.py", line 45, in import_features
    crs_from=shapefile_crs, crs_to=target_crs, always_xy=True, skip_equivalent=True
  File "/Users/simonw/.local/share/virtualenvs/shapefile-to-sqlite-53xajEHi/lib/python3.7/site-packages/pyproj/transformer.py", line 323, in from_crs
    area_of_interest=area_of_interest,
  File "pyproj/_transformer.pyx", line 313, in pyproj._transformer._Transformer.from_crs
  File "pyproj/_transformer.pyx", line 391, in pyproj._transformer._Transformer._init_from_crs
  File "pyproj/_transformer.pyx", line 216, in pyproj._transformer._Transformer._initialize_from_projobj
pyproj.exceptions.ProjError: Input is not a transformation.: (Internal Proj Error: proj_normalize_for_visualization: Object is not a CoordinateOperation created with proj_create_crs_to_crs)
```

**Comment by simonw** [comment]
Needs documentation.
